version: "3.9"

networks:
  eco:
    driver: bridge
volumes:
  ecopostgres:
    driver: local
    
services:

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - ecopostgres:/var/lib/postgresql/data
    networks:
      - eco
