FROM node:16-alpine as build

WORKDIR /app

ADD front-end .

ARG REACT_APP_BASE_URL_API

ENV REACT_APP_BASE_URL_API $REACT_APP_BASE_URL_API

RUN npm install
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]